name: Build and Package Bundles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package selected outputs
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          mkdir -p "$BRANCH_NAME/left_panel" "$BRANCH_NAME/right_panel"
          cp dist/left_panel/bundle.js "$BRANCH_NAME/left_panel/bundle.js"
          # Handle possible alternate spelling of right panel directory
          if [ -f dist/right_panel/bundle.js ]; then
            cp dist/right_panel/bundle.js "$BRANCH_NAME/right_panel/bundle.js"
          elif [ -f dist/rigth/bundle.js ]; then
            cp dist/rigth/bundle.js "$BRANCH_NAME/right_panel/bundle.js"
          fi
          cp manifest.json "$BRANCH_NAME/manifest.json"
          zip -r "${BRANCH_NAME}.zip" "$BRANCH_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-bundle
          path: ${{ github.ref_name }}.zip 