name: Release Tempalte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package selected outputs
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          APP_DIR="app"
          mkdir -p "$APP_DIR/left_panel" "$APP_DIR/right_panel"
          cp dist/left_panel/bundle.js "$APP_DIR/left_panel/bundle.js"
          # Handle possible alternate spelling of right panel directory
          if [ -f dist/right_panel/bundle.js ]; then
            cp dist/right_panel/bundle.js "$APP_DIR/right_panel/bundle.js"
          elif [ -f dist/rigth/bundle.js ]; then
            cp dist/rigth/bundle.js "$APP_DIR/right_panel/bundle.js"
          fi
          cp manifest.json "$APP_DIR/manifest.json"
          zip -r "${BRANCH_NAME}.zip" "$APP_DIR"

      # Create or update a GitHub Release for this branch/tag and attach the bundle ZIP
      - name: Publish release with asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
          name: Build for ${{ github.ref_name }} (run ${{ github.run_number }})
          files: ${{ github.ref_name }}.zip
          draft: false
          prerelease: false 